const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('fs')
const os = require('os')
const path = require('path')
const http = require('http')
const { createStore, createHandler } = require('../cc-settings')
function fixture(t) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'cc-settings-test-'))
  const project = path.join(root, 'project'), home = path.join(root, 'home'), backups = path.join(root, 'backups')
  fs.mkdirSync(project); fs.mkdirSync(home)
  t.after(() => fs.rmSync(root, { recursive: true, force: true }))
  return { root, project, home, backups, store: createStore({ project, home, backups }) }
}
test('document edits preserve originals and reject stale edits and arbitrary paths', t => {
  const { store, backups } = fixture(t)
  const first = store.readDocument('project')
  assert.equal(first.exists, false)
  const next = store.saveDocument('project', '# 原文\n', first.revision)
  store.saveDocument('project', '# 新版\n', next.revision)
  assert.throws(() => store.saveDocument('project', '覆盖', next.revision), { status: 409 })
  assert.equal(fs.readFileSync(path.join(backups, fs.readdirSync(backups)[0]), 'utf8'), '# 原文\n')
  assert.throws(() => store.readDocument('../secret'), { status: 400 })
})
test('model changes preserve hooks and permissions; global config stays untouched', t => {
  const { store, project, home } = fixture(t)
  fs.mkdirSync(path.join(project, '.claude'))
  const file = path.join(project, '.claude/settings.local.json')
  const settings = { permissions: { deny: ['Bash(rm:*)'] }, hooks: { Stop: [] }, model: 'sonnet' }
  fs.writeFileSync(file, JSON.stringify(settings))
  const before = store.readModel()
  store.saveModel('opus', before.revision)
  assert.deepEqual(JSON.parse(fs.readFileSync(file)), { ...settings, model: 'opus' })
  assert.equal(fs.existsSync(path.join(home, '.claude/settings.json')), false)
  assert.throws(() => store.saveModel('opus; rm -rf /', store.readModel().revision), { status: 400 })
})
test('symlink files cannot be edited through the panel', t => {
  const { store, project, root } = fixture(t)
  const other = path.join(root, 'other'); fs.writeFileSync(other, 'untouched')
  fs.symlinkSync(other, path.join(project, 'CLAUDE.md'))
  assert.throws(() => store.readDocument('project'), { status: 409 })
  assert.equal(fs.readFileSync(other, 'utf8'), 'untouched')
})
test('HTTP requires login even on localhost and supports round-trip save', async t => {
  const { store } = fixture(t)
  const handler = createHandler(store, token => token === 'fixture-only')
  const server = http.createServer((req, res) => handler(req, res, new URL(req.url, 'http://localhost')))
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  t.after(() => { server.closeAllConnections(); server.close() })
  const url = `http://127.0.0.1:${server.address().port}/raven/cc-settings`
  assert.equal((await fetch(url)).status, 401)
  const headers = { Authorization: 'Bearer fixture-only', 'Content-Type': 'application/json' }
  const first = await (await fetch(url, { headers })).json()
  const response = await fetch(url, { method: 'POST', headers, body: JSON.stringify({ scope: 'project', content: 'hello', revision: first.revision }) })
  assert.equal(response.status, 200)
  assert.equal((await response.json()).content, 'hello')
  assert.equal((await fetch(url, { method: 'POST', headers, body: '{' })).status, 400)
})
