const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { createUploadStore } = require('../crossing-uploads')

test('sent file survives temporary expiry and restart, without exposing arbitrary paths', async t => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'crossing-history-'))
  t.after(() => fs.rmSync(cwd, { recursive: true, force: true }))
  let now = Date.now()
  const store = createUploadStore({ cwd, now: () => now, ttl: 10 })
  const file = store.put({ name: '测试.txt', mime: 'text/plain', data: Buffer.from('fixture').toString('base64') }, 'owner')
  const inputs = await store.resolveInputs([{ id: file.id }], false, 'owner')
  now += 60000; store.sweep()
  const restored = createUploadStore({ cwd })
  const view = restored.historyContent(inputs)
  assert.equal(view[0].type, 'file')
  assert.equal(view[0].name, '测试.txt')
  assert.equal(view[0].url, 'data:text/plain;base64,Zml4dHVyZQ==')
  const unsafe = restored.historyContent([{ type: 'localImage', path: '/etc/passwd' }])
  assert.equal(unsafe[0].type, 'text')
  assert.ok(!JSON.stringify(unsafe).includes('/etc/passwd'))
})
